name: QDistRnd
version: "0.6.0"
license: "GPL-2.0-or-later"
date: 2021-10-07
description: |
    Calculate the distance of a q-ary quantum stabilizer code

authors:
    - name: Leonid P. Pryadko
      url: http://faculty.ucr.edu/~leonid
    - name: Vadim A. Shabashov
      url: https://sites.google.com/view/vadim-shabashov/

maintainers:
    - name: Leonid P. Pryadko
      url: http://faculty.ucr.edu/~leonid
    - name: Vadim A. Shabashov
      url: https://sites.google.com/view/vadim-shabashov/
    - name: Valerii K. Kozin
      url: mailto:kozin.valera@gmail.com

GAP: "4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "AutoDoc"
      version: "1.5"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "Guava"
      version: "3.14"
      url: "https://gap-packages.github.io/guava"

www: https://gap-packages.github.io/qdistrnd
readme: README
packageinfo: https://gap-packages.github.io/qdistrnd/PackageInfo.g

downloads:
    - name: tar.gz
      url: https://github.com/VadimShabashov/QDistRnd/releases/download/v0.6.0/qdistrnd-0.6.0tar.gz

abstract: |
    The GAP package <code>QDistRnd</code> 
    implements a probabilistic algorithm for finding the 
    minimum distance of a quantum code linear over a finite
    field GF(<var>q</var>).

status: other
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    QECC, quantum code, stabilizer code, quantum error correcting code, distance.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>PSK21</span>]   <b class='BibAuthor'>Pryadko, L. P., Shabashov, V. A. and Kozin, V. K.</b>,
     <i class='BibTitle'>QDistRnd, Calculate the distance of a q-ary quantum stabilizer code,
             Version 0.6.0</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/qdistrnd">https://gap-packages.github.io/qdistrnd</a></span>.
    </p>
    

bibtex: |
    @misc{ QDistRnd0.6.0,
      author =           {Pryadko, L. P. and Shabashov, V. A. and Kozin, V. K.},
      title =            {{QDistRnd}, Calculate the distance of a q-ary quantum stabilizer code, {V}ersion 0.6.0},
      month =            {Oct},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href                                                   {https://gap-packages.github.io/qdistrnd}
                          {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{qdistrnd}}},
      keywords =         {QECC; quantum code; stabilizer code; quantum error correcting code; distance},
      printedkey =       {PSK21}
    }

